language: python

install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - hash -r
        - conda config --set always_yes yes
        - conda update -q conda
        - conda install django bokeh sqlite=3.25.3
        - conda install -c conda-forge xraylib habanero
        # install xdi...
        - pushd $HOME
        - git clone -b XDI-autotools https://github.com/tschoonj/XAS-Data-Interchange
        - cd XAS-Data-Interchange/lib
        - autoreconf -fi
        - ./configure --prefix=$HOME/miniconda
        - make && make install
        - cd ../languages/python
        - python setup.py install
        - popd

script:
        - cd xasdb
        - python manage.py test xasdb1 -v 2


branches:
        only:
                - master

notifications:
        email:
                recipients:
                        - Tom.Schoonjans@me.com
                on_success: never
                on_failure: always
